/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://34siakbtprgopamk42avka6vn4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xaak2x3zxjddpa5szn7ctq6bwq",
    "aws_cognito_identity_pool_id": "us-east-1:68e90c84-8e13-4007-b33f-b989639b0717",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AyLKFH6zO",
    "aws_user_pools_web_client_id": "2p1drpl3s956maaq9j0cad1ac0",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "higley-temporary-bucket",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
